FROM node:14.16.1-buster
WORKDIR /app
COPY /. ./crackMyPassowrd/
WORKDIR /app/crackMyPassowrd
RUN npm i
ENV PORT="5000"
ENV CLIENT_URL="http://localhost:3000"
EXPOSE 5000
ENTRYPOINT [ "node", "/app/crackMyPassowrd/index.js"]